server:
  port: 8090
  context-path: /
debug: true
spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://sbs-dc-postgres:5432/sbsdatacentric?currentSchema=sbs
    username: sbsapi
    password: YMIN^hC]6tllt+r
    type: com.zaxxer.hikari.HikariDataSource
    validationQuery: SELECT 1
    hikari:
      maximum-pool-size: 5
      idle-timeout: 10000
      minimum-idle: 1
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      show-sql: true
      properties.hibernate.generate_statistics: false
management:
  context-path: /admin
  security:
    enabled: false